services:
  web:
    build: ./API
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/websites
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: